// Generated by scripts/generate_web_contract.py. Do not edit by hand.
export const BACKEND_CONTRACT = {
  "enums": {
    "artifactStatus": [
      "current",
      "stale"
    ],
    "artifactType": [
      "prd",
      "architecture",
      "business_rules",
      "integration_requirements",
      "approval_controls",
      "evaluation_plan",
      "implementation_spec"
    ],
    "assertionStatus": [
      "verified",
      "superseded",
      "disputed",
      "retired"
    ],
    "assessmentDeliveryMethod": [
      "ai_fde",
      "conventional"
    ],
    "assessmentOutcome": [
      "completed",
      "blocked",
      "abandoned"
    ],
    "assessmentPerspective": [
      "operator",
      "engineering"
    ],
    "claimKind": [
      "entity",
      "relationship",
      "rule",
      "exception"
    ],
    "claimMateriality": [
      "low",
      "material"
    ],
    "claimPredicate": [
      "GOVERNED_BY",
      "HANDS_OFF_TO",
      "IDENTIFIED_AS",
      "OWNS",
      "PRECEDES",
      "REQUIRES_APPROVAL",
      "USES"
    ],
    "claimStatus": [
      "candidate",
      "accepted",
      "rejected",
      "deferred"
    ],
    "contradictionResolutionType": [
      "accepted_exception",
      "not_a_conflict",
      "superseded",
      "override"
    ],
    "contradictionStatus": [
      "open",
      "investigating",
      "resolved",
      "accepted_exception",
      "not_a_conflict"
    ],
    "customerFactoryModelStatus": [
      "DRAFT",
      "APPROVED",
      "STALE"
    ],
    "deletionReceiptDataClassification": [
      "synthetic",
      "sanitized"
    ],
    "deletionReceiptStatus": [
      "processing",
      "completed",
      "failed"
    ],
    "deploymentPackageStatus": [
      "DRAFT",
      "READY_FOR_REVIEW",
      "APPROVED",
      "PUBLISHED",
      "SUPERSEDED",
      "REJECTED",
      "REVOKED",
      "STALE"
    ],
    "designPartnerDataClassification": [
      "PUBLIC",
      "INTERNAL",
      "CONFIDENTIAL",
      "RESTRICTED"
    ],
    "designPartnerQualificationState": [
      "CONFIGURED",
      "IN_PROGRESS",
      "BLOCKED",
      "QUALIFIED"
    ],
    "designPartnerQualificationStatus": [
      "ACTIVE",
      "SUSPENDED",
      "REVOKED"
    ],
    "economicCaseStatus": [
      "draft",
      "approved",
      "stale"
    ],
    "engagementDataClassification": [
      "synthetic",
      "sanitized"
    ],
    "engagementDataLifecycleStatus": [
      "active",
      "deletion_processing",
      "deletion_failed"
    ],
    "engagementLifecycleStage": [
      "qualify",
      "discover",
      "model",
      "map",
      "decide",
      "design",
      "economic_case",
      "specify"
    ],
    "entityType": [
      "company",
      "department",
      "team",
      "person",
      "role",
      "system",
      "process",
      "policy",
      "rule",
      "exception"
    ],
    "evidenceSourceType": [
      "upload",
      "operator_note",
      "fixture"
    ],
    "evidenceStatus": [
      "queued",
      "processing",
      "needs_review",
      "failed",
      "complete"
    ],
    "factoryOpportunityStatus": [
      "CANDIDATE",
      "ASSESSED",
      "RECOMMENDED",
      "SELECTED",
      "REJECTED",
      "STALE"
    ],
    "fdlcReadinessAssessmentStatus": [
      "DRAFT",
      "APPROVED",
      "STALE"
    ],
    "fdlcReadinessStage": [
      "DISCOVER",
      "DESIGN",
      "ASSEMBLE",
      "VALIDATE",
      "DEPLOY",
      "OPERATE",
      "IMPROVE"
    ],
    "fdlcReadinessStatus": [
      "NOT_STARTED",
      "IN_PROGRESS",
      "BLOCKED",
      "READY",
      "CONDITIONALLY_READY",
      "NOT_READY",
      "STALE"
    ],
    "operatorAuthMode": [
      "development",
      "oidc"
    ],
    "packageRetrievalResult": [
      "RETRIEVED",
      "DENIED_NOT_PUBLISHED",
      "DENIED_STALE",
      "DENIED_REVOKED",
      "DENIED_QUALIFICATION",
      "DENIED_INTEGRITY",
      "NOT_FOUND"
    ],
    "workflowAllocation": [
      "human",
      "software",
      "ai",
      "ai_human"
    ],
    "workflowGeneratedBy": [
      "system",
      "operator"
    ],
    "workflowKind": [
      "current",
      "target"
    ],
    "workflowStatus": [
      "draft",
      "approved",
      "stale"
    ],
    "workflowStepType": [
      "human_task",
      "software_task",
      "decision",
      "approval",
      "handoff"
    ]
  },
  "requiredResponseFields": {
    "assertion": [
      "id",
      "subject",
      "subject_entity_id",
      "predicate",
      "object",
      "object_entity_id",
      "value",
      "status",
      "confidence",
      "recorded_at",
      "evidence"
    ],
    "claim": [
      "id",
      "claim_kind",
      "subject_text",
      "predicate",
      "object_text",
      "summary",
      "normalized_payload",
      "confidence",
      "materiality",
      "status",
      "created_at",
      "provenance"
    ],
    "contradiction": [
      "id",
      "summary",
      "status",
      "blocking",
      "left_claim_id",
      "right_claim_id",
      "resolution_type",
      "resolution_reason",
      "resolved_by_id",
      "resolved_at",
      "created_at"
    ],
    "customerFactoryModel": [
      "id",
      "engagement_id",
      "version_number",
      "status",
      "organization",
      "systems",
      "repositories",
      "environments",
      "workflows",
      "policies",
      "authority_boundaries",
      "constraints",
      "risks",
      "baselines",
      "evidence_refs",
      "verified_claim_refs",
      "assumption_refs",
      "factory_opportunity_refs",
      "content_digest",
      "approved_at",
      "stale_reason",
      "created_at"
    ],
    "deliveryScorecard": [
      "engagement",
      "milestones",
      "claims",
      "contradictions",
      "packet",
      "provider",
      "assessments"
    ],
    "deploymentPackage": [
      "id",
      "engagement_id",
      "package_id",
      "package_version",
      "schema_version",
      "status",
      "issuer",
      "source",
      "target",
      "deployment_intent",
      "digest",
      "approval",
      "issued_at",
      "approved_at",
      "published_at",
      "state_reason",
      "created_at"
    ],
    "designPartnerQualification": [
      "id",
      "engagement_id",
      "partner_key",
      "organization",
      "status",
      "qualification_state",
      "authorized_users",
      "authorized_data_source_keys",
      "authorized_repository_refs",
      "allowed_workflow_classes",
      "data_classification",
      "retention_days",
      "authorization_basis_ref",
      "created_at",
      "updated_at"
    ],
    "economicCase": [
      "id",
      "version_number",
      "status",
      "source_target_workflow_id",
      "formula_version",
      "inputs",
      "outputs",
      "scenarios",
      "assumptions",
      "approved_at",
      "created_at",
      "updated_at"
    ],
    "engagement": [
      "id",
      "name",
      "slug",
      "workflow_name",
      "primary_outcome",
      "lifecycle_stage",
      "data_classification",
      "data_lifecycle_status",
      "retention_expires_at",
      "created_at",
      "updated_at"
    ],
    "engagementAssessment": [
      "id",
      "engagement_id",
      "evaluator_id",
      "delivery_method",
      "perspective",
      "outcome",
      "duration_minutes",
      "usefulness_score",
      "clarification_count",
      "rework_count",
      "workaround_count",
      "trust_failure_count",
      "notes",
      "created_at",
      "updated_at"
    ],
    "engagementDataLifecycle": [
      "status",
      "retention_expires_at",
      "membership_role",
      "latest_export",
      "export_current",
      "retention_blocked",
      "can_delete"
    ],
    "engagementDeletionReceipt": [
      "id",
      "engagement_id",
      "status",
      "data_classification",
      "export_id",
      "source_fingerprint",
      "archive_hash",
      "database_row_count",
      "evidence_object_count",
      "failure_code",
      "requested_at",
      "completed_at"
    ],
    "engagementWorkspace": [
      "engagement",
      "counts"
    ],
    "entity": [
      "id",
      "entity_type",
      "canonical_key",
      "display_name",
      "status",
      "created_at"
    ],
    "evidence": [
      "id",
      "engagement_id",
      "file_name",
      "content_type",
      "content_hash",
      "byte_count",
      "source_type",
      "source_timestamp",
      "design_partner_qualification_id",
      "authorized_source_key",
      "authorized_workflow_class",
      "data_classification",
      "status",
      "error_message",
      "created_at"
    ],
    "factoryHandoffPrerequisites": [
      "engagement_id",
      "organization_key",
      "organization_label",
      "workflow_name",
      "primary_outcome",
      "evidence_refs",
      "verified_claim_refs",
      "current_workflow_ref",
      "target_workflow_ref",
      "economic_case_ref",
      "implementation_artifact_refs"
    ],
    "factoryHandoffWorkspace": [
      "customer_model",
      "opportunities",
      "readiness",
      "packages",
      "latest_retrieval"
    ],
    "factoryOpportunity": [
      "id",
      "engagement_id",
      "opportunity_key",
      "version_number",
      "status",
      "name",
      "description",
      "source_workflow_ref",
      "customer_factory_model_id",
      "customer_factory_model_version",
      "value_score",
      "verifiability_score",
      "readiness_score",
      "risk_score",
      "autonomy_potential",
      "priority_score",
      "factors",
      "rubric",
      "rubric_version",
      "economics_ref",
      "evidence_refs",
      "rationale",
      "blockers",
      "recommendation",
      "content_digest",
      "selection_reason",
      "selected_at",
      "rejection_reason",
      "rejected_at",
      "stale_reason",
      "created_at"
    ],
    "fdlcReadinessAssessment": [
      "id",
      "engagement_id",
      "version_number",
      "status",
      "overall_status",
      "customer_factory_model_id",
      "customer_factory_model_version",
      "selected_opportunity_id",
      "selected_opportunity_version",
      "current_workflow_ref",
      "target_workflow_ref",
      "stages",
      "content_digest",
      "approved_at",
      "stale_reason",
      "created_at"
    ],
    "implementationArtifact": [
      "id",
      "artifact_type",
      "packet_version",
      "version_number",
      "status",
      "title",
      "content",
      "content_hash",
      "source_current_workflow_id",
      "source_target_workflow_id",
      "economic_case_id",
      "source_assertion_ids",
      "generated_at"
    ],
    "internalAlphaScorecard": [
      "program",
      "profile_count",
      "packet_complete_count",
      "accepted_material_claim_count",
      "total_provider_tokens",
      "engagements",
      "comparison"
    ],
    "operatingModel": [
      "entities",
      "assertions"
    ],
    "packageRetrievalEvent": [
      "id",
      "engagement_id",
      "package_id",
      "package_version",
      "requester_identity",
      "requester_system",
      "result",
      "digest",
      "correlation_id",
      "created_at"
    ],
    "provenance": [
      "claim_evidence_id",
      "evidence_segment_id",
      "evidence_asset_id",
      "file_name",
      "source_type",
      "source_timestamp",
      "locator",
      "quote",
      "start_offset",
      "end_offset"
    ],
    "workflow": [
      "id",
      "workflow_kind",
      "version_number",
      "name",
      "objective",
      "status",
      "source_workflow_id",
      "source_assertion_ids",
      "generated_by",
      "approved_at",
      "approval_reason",
      "created_at",
      "updated_at",
      "steps"
    ],
    "workflowStep": [
      "id",
      "step_key",
      "position",
      "name",
      "description",
      "step_type",
      "actor_label",
      "system_label",
      "allocation",
      "rationale",
      "controls",
      "source_assertion_id"
    ],
    "workflowWorkspace": [
      "current",
      "target"
    ]
  }
} as const;

export type BackendEnum<
  Name extends keyof typeof BACKEND_CONTRACT.enums,
> = (typeof BACKEND_CONTRACT.enums)[Name][number];

export type MissingBackendFields<
  Name extends keyof typeof BACKEND_CONTRACT.requiredResponseFields,
  Value,
> = Exclude<
  (typeof BACKEND_CONTRACT.requiredResponseFields)[Name][number],
  keyof Value
>;
