"""initial vertical slice

Revision ID: 0ef4baf84938
Revises:
Create Date: 2026-08-08 02:05:13.148779
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0ef4baf84938"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operators",
        sa.Column("external_subject", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operators")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_operators_external_subject")),
    )
    op.create_table(
        "engagements",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("primary_outcome", sa.Text(), nullable=False),
        sa.Column("lifecycle_stage", sa.String(length=32), nullable=False),
        sa.Column("data_classification", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "data_classification IN ('synthetic', 'sanitized')",
            name=op.f("ck_engagements_valid_data_classification"),
        ),
        sa.CheckConstraint(
            "lifecycle_stage IN ('qualify', 'discover', 'model', 'map')",
            name=op.f("ck_engagements_valid_lifecycle_stage"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["operators.id"],
            name=op.f("fk_engagements_created_by_id_operators"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_engagements")),
        sa.UniqueConstraint("created_by_id", "slug", name="engagement_slug_per_creator"),
    )
    op.create_table(
        "audit_events",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=160), nullable=False),
        sa.Column("target_type", sa.String(length=120), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_audit_events_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_engagement_created",
        "audit_events",
        ["engagement_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "engagement_members",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('owner', 'operator', 'viewer')", name=op.f("ck_engagement_members_valid_role")
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_engagement_members_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.id"],
            name=op.f("fk_engagement_members_operator_id_operators"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_engagement_members")),
        sa.UniqueConstraint("engagement_id", "operator_id", name="membership_identity"),
    )
    op.create_table(
        "evidence_assets",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("byte_count", sa.BigInteger(), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_type IN ('upload', 'operator_note', 'fixture')",
            name=op.f("ck_evidence_assets_valid_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'needs_review', 'failed', 'complete')",
            name=op.f("ck_evidence_assets_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["operators.id"],
            name=op.f("fk_evidence_assets_created_by_id_operators"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_evidence_assets_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_assets")),
        sa.UniqueConstraint(
            "engagement_id", "content_hash", name="evidence_content_per_engagement"
        ),
    )
    op.create_index(
        "ix_evidence_assets_engagement_status",
        "evidence_assets",
        ["engagement_id", "status"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_jobs_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_jobs_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("engagement_id", "idempotency_key", name="job_idempotency"),
    )
    op.create_index(
        "ix_jobs_engagement_available",
        "jobs",
        ["engagement_id", "status", "available_at"],
        unique=False,
    )
    op.create_table(
        "operating_entities",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=48), nullable=False),
        sa.Column("canonical_key", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("verified_by_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "entity_type IN ('company', 'department', 'team', 'person', 'role', "
            "'system', 'process', 'policy', 'rule', 'exception')",
            name=op.f("ck_operating_entities_valid_entity_type"),
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_operating_entities_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"],
            ["operators.id"],
            name=op.f("fk_operating_entities_verified_by_id_operators"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operating_entities")),
        sa.UniqueConstraint(
            "engagement_id", "entity_type", "canonical_key", name="entity_identity"
        ),
    )
    op.create_index(
        "ix_operating_entities_engagement_type",
        "operating_entities",
        ["engagement_id", "entity_type"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("aggregate_type", sa.String(length=120), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_outbox_events_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_events_unpublished",
        "outbox_events",
        ["published_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "evidence_segments",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("evidence_asset_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parser_name", sa.String(length=120), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_evidence_segments_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_asset_id"],
            ["evidence_assets.id"],
            name=op.f("fk_evidence_segments_evidence_asset_id_evidence_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_segments")),
        sa.UniqueConstraint("evidence_asset_id", "ordinal", name="evidence_segment_ordinal"),
    )
    op.create_index(
        "ix_evidence_segments_engagement_asset",
        "evidence_segments",
        ["engagement_id", "evidence_asset_id"],
        unique=False,
    )
    op.create_table(
        "extraction_runs",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("evidence_asset_id", sa.UUID(), nullable=False),
        sa.Column("extractor_name", sa.String(length=120), nullable=False),
        sa.Column("extractor_version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'complete', 'failed')",
            name=op.f("ck_extraction_runs_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_extraction_runs_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_asset_id"],
            ["evidence_assets.id"],
            name=op.f("fk_extraction_runs_evidence_asset_id_evidence_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_runs")),
    )
    op.create_index(
        "ix_extraction_runs_engagement_asset",
        "extraction_runs",
        ["engagement_id", "evidence_asset_id"],
        unique=False,
    )
    op.create_table(
        "candidate_claims",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("extraction_run_id", sa.UUID(), nullable=False),
        sa.Column("claim_kind", sa.String(length=32), nullable=False),
        sa.Column("subject_text", sa.String(length=512), nullable=False),
        sa.Column("predicate", sa.String(length=120), nullable=False),
        sa.Column("object_text", sa.String(length=1024), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("normalized_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("materiality", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "claim_kind IN ('entity', 'relationship', 'rule', 'exception')",
            name=op.f("ck_candidate_claims_valid_claim_kind"),
        ),
        sa.CheckConstraint(
            "materiality IN ('low', 'material')", name=op.f("ck_candidate_claims_valid_materiality")
        ),
        sa.CheckConstraint(
            "status IN ('candidate', 'accepted', 'rejected', 'deferred')",
            name=op.f("ck_candidate_claims_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_candidate_claims_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_runs.id"],
            name=op.f("fk_candidate_claims_extraction_run_id_extraction_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_claims")),
    )
    op.create_index(
        "ix_candidate_claims_engagement_status",
        "candidate_claims",
        ["engagement_id", "status"],
        unique=False,
    )
    op.create_table(
        "assertions",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("subject_entity_id", sa.UUID(), nullable=False),
        sa.Column("predicate", sa.String(length=120), nullable=False),
        sa.Column("object_entity_id", sa.UUID(), nullable=True),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("candidate_claim_id", sa.UUID(), nullable=False),
        sa.Column("verified_by_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('verified', 'superseded', 'disputed', 'retired')",
            name=op.f("ck_assertions_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_claim_id"],
            ["candidate_claims.id"],
            name=op.f("fk_assertions_candidate_claim_id_candidate_claims"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_assertions_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["object_entity_id"],
            ["operating_entities.id"],
            name=op.f("fk_assertions_object_entity_id_operating_entities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_entity_id"],
            ["operating_entities.id"],
            name=op.f("fk_assertions_subject_entity_id_operating_entities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"],
            ["operators.id"],
            name=op.f("fk_assertions_verified_by_id_operators"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assertions")),
        sa.UniqueConstraint("candidate_claim_id", name="assertion_source_claim"),
    )
    op.create_index(
        "ix_assertions_engagement_status", "assertions", ["engagement_id", "status"], unique=False
    )
    op.create_table(
        "claim_evidence",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("candidate_claim_id", sa.UUID(), nullable=False),
        sa.Column("evidence_segment_id", sa.UUID(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_claim_id"],
            ["candidate_claims.id"],
            name=op.f("fk_claim_evidence_candidate_claim_id_candidate_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_claim_evidence_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_segment_id"],
            ["evidence_segments.id"],
            name=op.f("fk_claim_evidence_evidence_segment_id_evidence_segments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_evidence")),
        sa.UniqueConstraint("candidate_claim_id", "evidence_segment_id", name="claim_segment"),
    )
    op.create_table(
        "contradictions",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("left_claim_id", sa.UUID(), nullable=False),
        sa.Column("right_claim_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('open', 'investigating', 'resolved', "
            "'accepted_exception', 'not_a_conflict')",
            name=op.f("ck_contradictions_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_contradictions_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["left_claim_id"],
            ["candidate_claims.id"],
            name=op.f("fk_contradictions_left_claim_id_candidate_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["right_claim_id"],
            ["candidate_claims.id"],
            name=op.f("fk_contradictions_right_claim_id_candidate_claims"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contradictions")),
        sa.UniqueConstraint("left_claim_id", "right_claim_id", name="contradiction_claim_pair"),
    )
    op.create_table(
        "review_decisions",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("candidate_claim_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "decision IN ('accepted', 'rejected', 'deferred')",
            name=op.f("ck_review_decisions_valid_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_claim_id"],
            ["candidate_claims.id"],
            name=op.f("fk_review_decisions_candidate_claim_id_candidate_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_review_decisions_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["operators.id"],
            name=op.f("fk_review_decisions_reviewer_id_operators"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_decisions")),
        sa.UniqueConstraint("candidate_claim_id", name="one_decision_per_candidate_claim"),
    )
    op.create_table(
        "assertion_evidence",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("assertion_id", sa.UUID(), nullable=False),
        sa.Column("evidence_segment_id", sa.UUID(), nullable=False),
        sa.Column("claim_evidence_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assertion_id"],
            ["assertions.id"],
            name=op.f("fk_assertion_evidence_assertion_id_assertions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["claim_evidence_id"],
            ["claim_evidence.id"],
            name=op.f("fk_assertion_evidence_claim_evidence_id_claim_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_assertion_evidence_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_segment_id"],
            ["evidence_segments.id"],
            name=op.f("fk_assertion_evidence_evidence_segment_id_evidence_segments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assertion_evidence")),
        sa.UniqueConstraint("assertion_id", "evidence_segment_id", name="assertion_segment"),
    )
    _install_row_security()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS ai_fde_can_access_engagement(uuid)")
    op.execute("DROP FUNCTION IF EXISTS ai_fde_current_operator_id()")
    op.drop_table("assertion_evidence")
    op.drop_table("review_decisions")
    op.drop_table("contradictions")
    op.drop_table("claim_evidence")
    op.drop_index("ix_assertions_engagement_status", table_name="assertions")
    op.drop_table("assertions")
    op.drop_index("ix_candidate_claims_engagement_status", table_name="candidate_claims")
    op.drop_table("candidate_claims")
    op.drop_index("ix_extraction_runs_engagement_asset", table_name="extraction_runs")
    op.drop_table("extraction_runs")
    op.drop_index("ix_evidence_segments_engagement_asset", table_name="evidence_segments")
    op.drop_table("evidence_segments")
    op.drop_index("ix_outbox_events_unpublished", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_operating_entities_engagement_type", table_name="operating_entities")
    op.drop_table("operating_entities")
    op.drop_index("ix_jobs_engagement_available", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_evidence_assets_engagement_status", table_name="evidence_assets")
    op.drop_table("evidence_assets")
    op.drop_table("engagement_members")
    op.drop_index("ix_audit_events_engagement_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("engagements")
    op.drop_table("operators")
    # ### end Alembic commands ###


def _install_row_security() -> None:
    op.execute(
        """
        CREATE FUNCTION ai_fde_current_operator_id()
        RETURNS uuid
        LANGUAGE sql
        STABLE
        AS $$
            SELECT NULLIF(current_setting('ai_fde.operator_id', true), '')::uuid
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION ai_fde_can_access_engagement(target_engagement_id uuid)
        RETURNS boolean
        LANGUAGE sql
        STABLE
        SECURITY DEFINER
        SET search_path = public, pg_temp
        SET row_security = off
        AS $$
            SELECT EXISTS (
                SELECT 1
                FROM engagements
                WHERE id = target_engagement_id
                  AND created_by_id = ai_fde_current_operator_id()
            ) OR EXISTS (
                SELECT 1
                FROM engagement_members
                WHERE engagement_id = target_engagement_id
                  AND operator_id = ai_fde_current_operator_id()
            )
        $$
        """
    )
    op.execute("REVOKE ALL ON FUNCTION ai_fde_can_access_engagement(uuid) FROM PUBLIC")
    op.execute("GRANT EXECUTE ON FUNCTION ai_fde_can_access_engagement(uuid) TO ai_fde_app")
    op.execute("GRANT EXECUTE ON FUNCTION ai_fde_current_operator_id() TO ai_fde_app")

    op.execute("ALTER TABLE engagements ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY engagements_operator_access ON engagements
        FOR ALL TO ai_fde_app
        USING (ai_fde_can_access_engagement(id))
        WITH CHECK (created_by_id = ai_fde_current_operator_id())
        """
    )

    scoped_tables = (
        "engagement_members",
        "audit_events",
        "evidence_assets",
        "jobs",
        "operating_entities",
        "outbox_events",
        "evidence_segments",
        "extraction_runs",
        "candidate_claims",
        "assertions",
        "claim_evidence",
        "contradictions",
        "review_decisions",
        "assertion_evidence",
    )
    for table_name in scoped_tables:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table_name}_operator_access ON {table_name}
            FOR ALL TO ai_fde_app
            USING (ai_fde_can_access_engagement(engagement_id))
            WITH CHECK (ai_fde_can_access_engagement(engagement_id))
            """
        )

    op.execute("GRANT USAGE ON SCHEMA public TO ai_fde_app")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ai_fde_app")
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ai_fde_app"
    )
