"""workflow economics and specifications

Revision ID: 5c01e3b1557b
Revises: 0ef4baf84938
Create Date: 2026-08-08 02:32:55.990209
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5c01e3b1557b"
down_revision: str | None = "0ef4baf84938"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_versions",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("workflow_kind", sa.String(length=24), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("source_workflow_id", sa.UUID(), nullable=True),
        sa.Column("source_assertion_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_by", sa.String(length=24), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "generated_by IN ('system', 'operator')",
            name=op.f("ck_workflow_versions_valid_generated_by"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'stale')",
            name=op.f("ck_workflow_versions_valid_status"),
        ),
        sa.CheckConstraint(
            "workflow_kind IN ('current', 'target')",
            name=op.f("ck_workflow_versions_valid_workflow_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["operators.id"],
            name=op.f("fk_workflow_versions_approved_by_id_operators"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["operators.id"],
            name=op.f("fk_workflow_versions_created_by_id_operators"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_workflow_versions_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_workflow_id"],
            ["workflow_versions.id"],
            name=op.f("fk_workflow_versions_source_workflow_id_workflow_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_versions")),
        sa.UniqueConstraint(
            "engagement_id", "workflow_kind", "version_number", name="workflow_version_identity"
        ),
    )
    op.create_index(
        "ix_workflow_versions_engagement_kind",
        "workflow_versions",
        ["engagement_id", "workflow_kind", "status"],
        unique=False,
    )
    op.create_table(
        "economic_cases",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("source_target_workflow_id", sa.UUID(), nullable=False),
        sa.Column("formula_version", sa.String(length=64), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'stale')", name=op.f("ck_economic_cases_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["operators.id"],
            name=op.f("fk_economic_cases_approved_by_id_operators"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["operators.id"],
            name=op.f("fk_economic_cases_created_by_id_operators"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_economic_cases_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_target_workflow_id"],
            ["workflow_versions.id"],
            name=op.f("fk_economic_cases_source_target_workflow_id_workflow_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_economic_cases")),
        sa.UniqueConstraint("engagement_id", "version_number", name="economic_case_version"),
    )
    op.create_index(
        "ix_economic_cases_engagement_status",
        "economic_cases",
        ["engagement_id", "status"],
        unique=False,
    )
    op.create_table(
        "implementation_artifacts",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("artifact_type", sa.String(length=48), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_current_workflow_id", sa.UUID(), nullable=False),
        sa.Column("source_target_workflow_id", sa.UUID(), nullable=False),
        sa.Column("economic_case_id", sa.UUID(), nullable=False),
        sa.Column("source_assertion_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_by_id", sa.UUID(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "artifact_type IN ('implementation_spec')",
            name=op.f("ck_implementation_artifacts_valid_artifact_type"),
        ),
        sa.CheckConstraint(
            "status IN ('current', 'stale')", name=op.f("ck_implementation_artifacts_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["economic_case_id"],
            ["economic_cases.id"],
            name=op.f("fk_implementation_artifacts_economic_case_id_economic_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_implementation_artifacts_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_id"],
            ["operators.id"],
            name=op.f("fk_implementation_artifacts_generated_by_id_operators"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_current_workflow_id"],
            ["workflow_versions.id"],
            name=op.f("fk_implementation_artifacts_source_current_workflow_id_workflow_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_target_workflow_id"],
            ["workflow_versions.id"],
            name=op.f("fk_implementation_artifacts_source_target_workflow_id_workflow_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_implementation_artifacts")),
        sa.UniqueConstraint(
            "engagement_id", "artifact_type", "version_number", name="artifact_version_identity"
        ),
    )
    op.create_index(
        "ix_implementation_artifacts_engagement_status",
        "implementation_artifacts",
        ["engagement_id", "status"],
        unique=False,
    )
    op.create_table(
        "workflow_steps",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("workflow_version_id", sa.UUID(), nullable=False),
        sa.Column("step_key", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("step_type", sa.String(length=32), nullable=False),
        sa.Column("actor_label", sa.String(length=255), nullable=True),
        sa.Column("system_label", sa.String(length=255), nullable=True),
        sa.Column("allocation", sa.String(length=24), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("controls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_assertion_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "allocation IN ('human', 'software', 'ai', 'ai_human')",
            name=op.f("ck_workflow_steps_valid_allocation"),
        ),
        sa.CheckConstraint(
            "step_type IN ('human_task', 'software_task', 'decision', 'approval', 'handoff')",
            name=op.f("ck_workflow_steps_valid_step_type"),
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagements.id"],
            name=op.f("fk_workflow_steps_engagement_id_engagements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_assertion_id"],
            ["assertions.id"],
            name=op.f("fk_workflow_steps_source_assertion_id_assertions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_workflow_steps_workflow_version_id_workflow_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_steps")),
        sa.UniqueConstraint("workflow_version_id", "step_key", name="workflow_step_identity"),
    )
    op.create_index(
        "ix_workflow_steps_engagement_workflow",
        "workflow_steps",
        ["engagement_id", "workflow_version_id"],
        unique=False,
    )
    op.add_column(
        "contradictions", sa.Column("resolution_type", sa.String(length=32), nullable=True)
    )
    op.add_column("contradictions", sa.Column("resolution_reason", sa.Text(), nullable=True))
    op.add_column("contradictions", sa.Column("resolved_by_id", sa.UUID(), nullable=True))
    op.add_column(
        "contradictions", sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_contradictions_resolved_by_id_operators"),
        "contradictions",
        "operators",
        ["resolved_by_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        "valid_resolution_type",
        "contradictions",
        "resolution_type IS NULL OR resolution_type IN "
        "('accepted_exception', 'not_a_conflict', 'superseded', 'override')",
    )
    op.drop_constraint(op.f("ck_engagements_valid_lifecycle_stage"), "engagements", type_="check")
    op.create_check_constraint(
        "valid_lifecycle_stage",
        "engagements",
        "lifecycle_stage IN ('qualify', 'discover', 'model', 'map', 'decide', "
        "'design', 'economic_case', 'specify')",
    )
    for table_name in (
        "workflow_versions",
        "workflow_steps",
        "economic_cases",
        "implementation_artifacts",
    ):
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table_name}_operator_access ON {table_name}
            FOR ALL TO ai_fde_app
            USING (ai_fde_can_access_engagement(engagement_id))
            WITH CHECK (ai_fde_can_access_engagement(engagement_id))
            """
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO ai_fde_app")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_engagements_valid_lifecycle_stage"), "engagements", type_="check")
    op.create_check_constraint(
        "valid_lifecycle_stage",
        "engagements",
        "lifecycle_stage IN ('qualify', 'discover', 'model', 'map')",
    )
    op.drop_constraint(
        op.f("ck_contradictions_valid_resolution_type"), "contradictions", type_="check"
    )
    op.drop_constraint(
        op.f("fk_contradictions_resolved_by_id_operators"), "contradictions", type_="foreignkey"
    )
    op.drop_column("contradictions", "resolved_at")
    op.drop_column("contradictions", "resolved_by_id")
    op.drop_column("contradictions", "resolution_reason")
    op.drop_column("contradictions", "resolution_type")
    op.drop_index("ix_workflow_steps_engagement_workflow", table_name="workflow_steps")
    op.drop_table("workflow_steps")
    op.drop_index(
        "ix_implementation_artifacts_engagement_status", table_name="implementation_artifacts"
    )
    op.drop_table("implementation_artifacts")
    op.drop_index("ix_economic_cases_engagement_status", table_name="economic_cases")
    op.drop_table("economic_cases")
    op.drop_index("ix_workflow_versions_engagement_kind", table_name="workflow_versions")
    op.drop_table("workflow_versions")
    # ### end Alembic commands ###
