CREATE ROLE ai_fde_owner LOGIN PASSWORD 'ai_fde_owner' NOINHERIT;
CREATE ROLE ai_fde_app LOGIN PASSWORD 'ai_fde_app' NOINHERIT NOBYPASSRLS;

ALTER DATABASE ai_fde OWNER TO ai_fde_owner;
GRANT CONNECT ON DATABASE ai_fde TO ai_fde_app;
CREATE EXTENSION IF NOT EXISTS vector;
